apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy-container
          image: your-image
          env:
            - name: TARGET_URL
              valueFrom:
                configMapKeyRef:
                  name: proxy-config
                  key: TARGET_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: proxy-config
                  key: PORT
          ports:
            - containerPort: 8734
---
apiVersion: v1
kind: Service
metadata:
  name: http-proxy-service
  namespace: proxy
spec:
  selector:
    app: http-proxy
  ports:
    - protocol: TCP
      port: 8734
      targetPort: 8734
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-proxy-ingress-route
  namespace: proxy
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: http-proxy-service
          port: 8734
