apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-proxy-deployment
  namespace: clustershift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-proxy-deployment
  template:
    metadata:
      labels:
        app: http-proxy-deployment
    spec:
      containers:
        - name: proxy-container
          image: ghcr.io/romankudravcev/reverse-proxy-http:latest
          env:
            - name: TARGET_URL
              valueFrom:
                configMapKeyRef:
                  name: http-proxy-config
                  key: TARGET_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: http-proxy-config
                  key: PORT
          ports:
            - containerPort: 8734
---
apiVersion: v1
kind: Service
metadata:
  name: http-proxy-service
  namespace: clustershift
spec:
  selector:
    app: http-proxy-deployment
  ports:
    - protocol: TCP
      port: 8734
      targetPort: 8734
  type: ClusterIP
